export const ERROR_CODES = Object.freeze({
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  BOOKING_CONFLICT: "BOOKING_CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});
